NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
VERSION = "2.0.0"

[[CURRENCIES]]
code = "MACRO"
issuer = "GD73SAHCYBQ3CWD76UMJHDPLUUKIXELXWPLZVNLMW2DQZJQLYOWP45TO"
name = "Macrohard Token"
desc = "Macrohard is a token built on the Stellar Network with a total supply of 10 Billion."
image = "https://macrohard.io/macrohard.png"
